# Generated by Django 4.2.4 on 2023-10-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("Cooking_Time", models.CharField(max_length=255)),
                ("Serving_Size", models.CharField(max_length=255)),
                ("Ingredients", models.TextField(default="")),
                ("Directions", models.TextField(default="")),
            ],
        ),
    ]
