# Generated by Django 4.2.4 on 2023-10-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rName", models.CharField(max_length=255)),
                ("rTime", models.CharField(max_length=255)),
                ("rSize", models.CharField(max_length=255)),
            ],
        ),
    ]
