# Generated by Django 4.2.4 on 2023-10-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe", name="directions", field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="recipe", name="ingredients", field=models.TextField(default=""),
        ),
    ]
